/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.DepartmentController;
import controllers.EmployeeController;
import controllers.LocationController;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Department;
import models.Employee;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;
//import tools.DBConnection;

/**
 *
 * @author milhamafemi
 */
public class DepartmentView extends javax.swing.JPanel {

    DefaultTableModel myTable = new DefaultTableModel();
//    DBConnection connection = new DBConnection();
    private SessionFactory factory = HibernateUtil.getSessionFactory();
    private DepartmentController dc = new DepartmentController(factory);
    private EmployeeController ec = new EmployeeController(factory);
    private LocationController lc = new LocationController(factory);

    private List<models.Department> departmentList = new ArrayList<>();
    private List<models.Employee> employeeList = new ArrayList<>();
    private List<models.Location> locationList = new ArrayList<>();

    
    private DefaultTableModel tableModel;
    /**
     * Creates new form DepartmentView3
     */
    public DepartmentView() {
        initComponents();
        tableData(dc.getAll());
        setComboBox();        
    }

    private boolean konfirmasi() {
        if (tfDeptName.equals("") || tfDeptId.equals("") || cbManagerId.getSelectedIndex() == 0 || cbLocId.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data tidak boleh kosong");
            return false;
        }
        return true;
    }

    private boolean isEmpty() {
         if (dc.getById(tfDeptId.getText()).equals("")) {
            return true;
        }
        return false;
    }

    private void tableData(List<models.Department> dept) {
        Object[] columnNames = {"Nomor", "Department Id", "Department Name", "Manager Id", "Location Id"};
        Object[][] data = new Object[dept.size()][columnNames.length];
        for (int i = 0; i < data.length; i++) {
            data[i][0] = (i + 1);
            data[i][1] = dept.get(i).getId();
            data[i][2] = dept.get(i).getName();
            if (dept.get(i).getManager()!=null)data[i][3] = dept.get(i).getManager().getId()+"";
            else data[i][3] = "";
            if (dept.get(i).getLocation()!=null)data[i][4] = dept.get(i).getLocation().getId()+"";
            else data[i][4] = "";
//            data[i][3] = dept.get(i).getManager().getId();
//            data[i][4] = dept.get(i).getLocation();
        }
        myTable = new DefaultTableModel(data, columnNames);
        tbDepartment.setModel(myTable);
    }

    private void clean() {
        tfDeptId.setEnabled(true);
        tfDeptId.setText("");
        tfDeptName.setText("");
        tfSearch.setText("");
        cbManagerId.setSelectedIndex(0);
        cbLocId.setSelectedIndex(0);
    }

    private void filterHuruf(KeyEvent a) {
        if (Character.isAlphabetic(a.getKeyChar())) {
            a.consume();
            JOptionPane.showMessageDialog(null, "Pada kolom ID Department Hanya bisa memasukkan angka");
        }
    }

    private void setComboBox() {
//        for (models.Employee employee : ec.getAll()) {
//            cbManagerId.addItem(employee.getEmployeeList()+ " - " + employee.getLastName());
//        }

        for (models.Department department : departmentList) {
            for (Employee employee : department.getEmployeeList()) {
                cbManagerId.addItem(employee.getId()+ " - " + employee.getLastName());
            }
        }
        
        for (Department department : departmentList) {
            if (!locationList.contains(department.getLocation()))locationList.add(new models.Location(department.getLocation().getId(),department.getLocation().getCity()));
        }
        
        for (models.Location location : lc.getData()) {
            cbLocId.addItem(location.getId() + " - " + location.getStreetAddress());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeptName = new javax.swing.JLabel();
        lblDept = new javax.swing.JLabel();
        lblManagerId = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btDelete = new javax.swing.JButton();
        lblLocationId = new javax.swing.JLabel();
        tfDeptId = new javax.swing.JTextField();
        tfDeptName = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDepartment = new javax.swing.JTable();
        comboSearch = new javax.swing.JComboBox<>();
        lblDeptId = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        cbManagerId = new javax.swing.JComboBox<>();
        cbLocId = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDeptName.setText("Department Name");
        add(lblDeptName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, -1, -1));

        lblDept.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDept.setText("Department");
        add(lblDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 9, -1, -1));

        lblManagerId.setText("Manager Id");
        add(lblManagerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 135, -1, -1));
        add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 56, 134, -1));

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 201, 101, -1));

        lblLocationId.setText("Location Id");
        add(lblLocationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 168, -1, -1));
        add(tfDeptId, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 56, 210, -1));
        add(tfDeptName, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 93, 210, -1));

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 201, 97, -1));

        tbDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDepartmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDepartment);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 246, 631, 179));

        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search", "Search By Id", "Show All" }));
        comboSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSearchActionPerformed(evt);
            }
        });
        add(comboSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 92, 134, -1));

        lblDeptId.setText("Deprartment id");
        add(lblDeptId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, -1, -1));

        jLabel5.setText("Search");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 60, -1, -1));

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 130, 134, -1));

        btClose.setText("X");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });
        add(btClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 6, -1, -1));

        cbManagerId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        add(cbManagerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 130, 210, -1));

        cbLocId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        add(cbLocId, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 168, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        String id = tfDeptId.getText();
        if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
        } else {
            try {
                int reply = JOptionPane.showConfirmDialog(null,
                        "Anda yakin akan menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
                );
                if (reply == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(null, dc.delete(id));
                    clean();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tableData(dc.getAll());
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        if (isEmpty()) {
            JOptionPane.showMessageDialog(null, dc.insert(tfDeptId.getText(), tfDeptName.getText(),
cbManagerId.getSelectedItem().toString().split(" - ")[0], cbLocId.getSelectedItem().toString().split(" - ")[0]));
     } else {
            try {
                int reply = JOptionPane.showConfirmDialog(null, "Anda yakin untuk melakukan perubahan data?",
                        "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (reply == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(null, dc.update(tfDeptId.getText(), tfDeptName.getText(),
                            cbManagerId.getSelectedItem().toString().split(" - ")[0], cbLocId.getSelectedItem().toString().split(" - ")[0]));

                    clean();
                    tableData(dc.getAll());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        clean();
        tableData(dc.getAll());
    }//GEN-LAST:event_btSaveActionPerformed

    private void tbDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDepartmentMouseClicked
        // TODO add your handling code here:
        tfDeptId.setText(tbDepartment.getValueAt(tbDepartment.getSelectedRow(), 1).toString());
        tfDeptName.setText(tbDepartment.getValueAt(tbDepartment.getSelectedRow(), 2).toString());
//        jTextDeptManagerId.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        for (int i = 0; i < cbManagerId.getItemCount(); i++) {
            if (cbManagerId.getItemAt(i).split(" - ")[0].equals(tbDepartment.getValueAt(tbDepartment.getSelectedRow(), 3).toString())) {
                cbManagerId.setSelectedIndex(i);
            }
        }
//        jTextLocId.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        for (int i = 0; i < cbLocId.getItemCount(); i++) {
            if (cbLocId.getItemAt(i).split(" - ")[0].equals(tbDepartment.getValueAt(tbDepartment.getSelectedRow(), 4).toString())) {
                cbLocId.setSelectedIndex(i);
            }
        }

        tfDeptId.setEnabled(false);
    }//GEN-LAST:event_tbDepartmentMouseClicked

    private void comboSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSearchActionPerformed
        // TODO add your handling code here:
        String cari = tfSearch.getText();
        if (cari != "" && comboSearch.getSelectedItem() == "Search By Id") {
            //tableData(dc.getById(cari));
            Department tampungan = dc.getById(cari);
            tfDeptId.setText(tampungan.getId() + "");
            tfDeptName.setText(tampungan.getName());
            cbManagerId.setSelectedItem(tampungan.getManager());
            
            cbLocId.setSelectedItem(tampungan.getLocation());
        } else if (cari != "" && comboSearch.getSelectedItem() == "Search") {
            tableData(dc.seachBy(cari));
        } else {
            tableData(dc.getAll());
        }
    }//GEN-LAST:event_comboSearchActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        clean();
    }//GEN-LAST:event_btClearActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbLocId;
    private javax.swing.JComboBox<String> cbManagerId;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDept;
    private javax.swing.JLabel lblDeptId;
    private javax.swing.JLabel lblDeptName;
    private javax.swing.JLabel lblLocationId;
    private javax.swing.JLabel lblManagerId;
    private javax.swing.JTable tbDepartment;
    private javax.swing.JTextField tfDeptId;
    private javax.swing.JTextField tfDeptName;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

}
